### PR TITLE
Added possibility to configure edgeHitWidth

### PR DESCRIPTION
**Pull request by seb0zz**
* edgeHitWidth can now be passed as prop value
* added WebStorm (IntelliJ) IDE folder to .gitignore
* Adjusted README file

### CODE REVIEW

**Comment by Kureev** [comment]
Thanks <3

**Comment by niftylettuce** [comment]
Nice!

**Comment by niftylettuce** [comment]
I just took a quick min to test this, and it doesn't work.  Can you confirm?  I passed `edgeHitWidth` as a prop to `<SideMenu />` with a value of 200, and its still only defaulting to 60 or so...

**Comment by seb0zz** [comment]
Could you check if your prop is properly passed by adding some console logs in the index.js file?

**Comment by niftylettuce** [comment]
I just followed the Readme... I can check

**Comment by Kureev** [comment]
I haven't bumped the version yet. Sure you get the code from master, @niftylettuce ?

**Comment by niftylettuce** [comment]
Ah, that's the reason why.  You need to bump version please! :+1:

**Comment by niftylettuce** [comment]
Espec if you put it in master/Readme.md, then people think latest version has these features.

**Comment by niftylettuce** [comment]
Please publish a new version already to NPM....  I had to fork to my own repo because of this delay.

It's extremely bad practice to publish to Readme.md without also updating your package that's readily available for download in NPM.  I guarantee a lot of other people that don't know any better are scratching their heads and DOM inspecting right now.

**Comment by Kureev** [comment]
Published `0.14.4` with this commit. 

P.S. Dear @niftylettuce, I'd like to ask you to change your style of communication. I develop and maintain this project just because it's fun and people appreciate what I'm doing. Attempts to push me fix something wouldn't have any positive effect for sure. If you want to help this project - submit your PRs instead.

**Comment by niftylettuce** [comment]
I don't have control of the NPM package,  and it's bad practice to submit a
version update pull request

**Comment by niftylettuce** [comment]
Thank you @Kureev for publishing this version!  Apologies if my communication was not received as I intended.

**Pull request merged**
