### PR TITLE
Add "touchToClose" functionality.

### PR DESCRIPTION
**Pull request by skevy**

### CODE REVIEW

**Comment by skevy** [comment]
@alinz @Kureev check out 0a30640

**Comment by skevy** [comment]
I'm doing stupid stuff with my rebasing. Give me a minute to fix.

**Comment by skevy** [comment]
Ok. all set now. :)

**Comment by Kureev** [comment]
Looks good to me :+1: 
Thanks! Now testing time!

**Comment by Kureev** [comment]
Working like a charm. `0.8.0` released.

**Comment by alinz** [comment]
:+1:

**Pull request merged**
