### PR TITLE
Allow menu to open programmatically and option to disable gestures

### PR DESCRIPTION
**Pull request by dvcrn**
Hello,

I found myself in a situation where I wanted to open the sidebar whenever I fire a certain event. This PR adds that kind of functionality. 

Secondly, I added the option to disable gestures for opening the sidebar (for example when moving around in a MapView). I am not 100% sure if using `componentWillReceiveProps` for creating the responders is the right thing to do :tongue:

### CODE REVIEW

**Comment by Kureev** [comment]
Can you rebase form current HEAD? I'd like to merge it, but after merging your second PR I can't.

**Comment by dvcrn** [comment]
Looks like I messed the rebase up a bit. Re-added the commits manually, so everything should be there now.

**Comment by Kureev** [comment]
Thanks a lot, man!

**Comment by dvcrn** [comment]
No problem! Once you tested the chances, could you also release it? Then I can get rid of my repo :)

**Comment by Kureev** [comment]
Already done. Check `0.3.0` :+1:

**Pull request merged**
