### PR TITLE
fixed #48 updated onChange to provide accurate data

### LINKED ISSUE #48: I need to be updated as slide menu is dragged.
@Kureev, @skevy, have you guys seen Spotify app? As soon as you start dragging the menu, there is a nice animation happen behind the scene. Unfortunately there is no way for us to do this in current version. So I started to update the `onChange` method. So now, as soon as menu gets dragged, onChange method gets called with a value between 0 and 1. Zero means slide menu is completely close, and 1 means that slide menu is opened. 

I will do the PR in few mins.

p.s. I think we should start rewrite the code in `class` way. ~~I really don't like using `setNativeProps`~~.

### PR DESCRIPTION
**Pull request by alinz**
#48

### CODE REVIEW

**Comment by Kureev** [comment]
I'd prefer you make a solution with passing optional callbacks instead of hardcoding them. So the point is to allow users create custom animation (and control it) during the swipe, if I understood correct. But not all of them will want to implement this. Also, I'm not sure about the performance part of this solution. But still, I'm not against this, just make it optional.

**Comment by alinz** [comment]
I don't like it either. Give me more time to find a better solution. let's keep this ticket open and I will keep pushing my branch and once I'm ready I let you know to take a look at it.

**Comment by alinz** [comment]
@Kureev would you please take a look at [this](https://github.com/alinz/react-native-side-menu/commit/33d20e3b7b3d74c7f07e3090973bc5242c7922d2) and [that](https://github.com/alinz/react-native-side-menu/commit/47e5582b11209cec388104da358a6bfc082fc57e)? and I've been extremely busy with code. I should be back to crush all those bugs soon.

**Comment by alinz** [comment]
I will close this PR since it's no longer relevant! This can be done by your new API `animationFunction`. Thanks

**Pull request closed without merging**
