### PR TITLE
added onChange prop to SideMenu component.

### PR DESCRIPTION
**Pull request by alinz**
I have added a little bit of code to get this feature to work. So I added `onChange` props which will be called once Side Menu component closes or opens. I think it is useful for some scenarios. see #23

### CODE REVIEW

**Comment by alinz** [comment]
Here's an example of what this pull request can do.
So the onChange will be fired once the SideMenu opens or closes and one can access internal variable via `refs`.

```js
class MyAwesomeApp extends React.Component {
  constructor(props) {
    super(props);
  }

  onChange() {
    console.log(this.refs.sideMenu.isOpen);
  }

  render() {
    return (
      <SideMenu onChange={this.onChange.bind(this)} ref="sideMenu" menu={<Menu/>}>
        <Main/>
      </SideMenu>
    );
  }
}
```

**Comment by Kureev** [comment]
#23

**Comment by alinz** [comment]
@Kureev, Here's the PR for issue #23.

**Comment by Kureev** [comment]
Perfect!

**Pull request merged**
