### PR TITLE
fix orientation

### LINKED ISSUE #69: Main content layout doesn't stretch when rotate device
When we rotate device (for example, rotate iphone left or right), everything will automatically adjust from portrait mode to landscape mode for all react native UI components on ios8 devices. But this feature broken when we add side menu.

Here are some pictures and codes:

screen shot 2015-07-15 at 9 46 55 pm
screen shot 2015-07-15 at 9 47 45 pm

screen shot 2015-07-15 at 9 55 04 pm

We can see that top SegmentedControl and bottom TabBar all stretched correctly, but center content which wrapped in a SideMenu tag will always keep the portrait mode width (Even we start with landscape mode, it will still use portrait width, this is weird) 

                <SideMenu
                    ref='sideMenu'
                    openMenuOffset={Constants.STYLE.SIDE_MENU_WIDTH}
                    animation={'spring'}
                    disableGestures={true}
                    menu={<ReportMenu report={this.props.report}/>}>

                    <View style={styles.container}>
                             some contents here
                    </View>
                </SideMenu>

But if we remove side menu, everything works great when we rotate device (see background color):

screen shot 2015-07-15 at 10 01 13 pm

screen shot 2015-07-15 at 10 04 56 pm

                    <View style={styles.container}>
                             some contents here
                    </View>

Use flex: 1 style doesn't help. Any solution or suggestion?

### PR DESCRIPTION
**Pull request by skv-headless**
based on https://github.com/facebook/react-native/issues/2031#issuecomment-122684864
closes #69

### CODE REVIEW

**Comment by Kureev** [comment]
Man, so many thanks! Can you also remove `deviceScreen` from the file? Right after that I'll merge it :+1:

**Comment by skv-headless** [comment]
Dimensions used in 3 places:
1) **menu styles** https://github.com/Kureev/react-native-side-menu/blob/master/styles.js#L22
I tried to remove it and example works good without it.
 
2) **openMenuOffset** https://github.com/Kureev/react-native-side-menu/blob/master/index.js#L18
3) **barrierForward** https://github.com/Kureev/react-native-side-menu/blob/master/index.js#L31
I think menu should be fixed size. It should not depend on orientation.

@Kureev what do you think about all cases?

**Comment by Kureev** [comment]
I agree, `1` is a legacy style already. `2` & `3` should be replaced by numbers (need to take a look which offsets are common for this cases).

**Comment by skv-headless** [comment]
Here is screenshot from youtube(almost full width) and I saw same behaviour in other apps.
I think current solution for openMenuOffset and barrierForward are good. Anyway we able to customize this via props.  
c6c385339c488ac9c5a9ecd 73be88928ee8863aeb8ce76449bpimgpsh_fullsize_distr

**Comment by Kureev** [comment]
Thanks a lot! <3

**Comment by Kureev** [comment]
`0.14.2` has been released with this patch

**Pull request merged**
