### PR TITLE
Set useNativeDriver to improving performance of animations

### PR DESCRIPTION
**Pull request by BenClaveau**

### CODE REVIEW

**Comment by putuyoga** [comment]
any chance to review & merge this ? @Kureev ? would be great to improve the performance with `useNativeDriver`

**Comment by itanhduy** [comment]
Currently the animation is slow. We need to take a look about this request.

**Comment by jcarioti** [comment]
What’s going on with this? This is such a trivial change and it’s been pending for over a year?

**Comment by Kureev** [comment]
👋! This repository is not actively maintained, so it might take time to see the change (due to the overwhelming amount of notifications from other projects). Sorry for taking a bloody year to merge such a change in. 

Thank you very much for working on this 🙇

**Comment by jcarioti** [comment]
> 👋! This repository is not actively maintained, so it might take time to see the change (due to the overwhelming amount of notifications from other projects). Sorry for taking a bloody year to merge such a change in.
> 
> Thank you very much for working on this 🙇

Awesome, thank you! Can you publish the latest changes to NPM so we can use the native driver changes? Using the dependency as a link to the latest commit does not work due to the nature of how the prepublish scripts work.

**Comment by hoyleg** [comment]
@Kureev +1 to @jcarioti's request to have this published to NPM.  This would be really appreciated by us :)

**Comment by Karniej** [comment]
Is there a chance for a build on npm ? :) @Kureev

**Comment by nes123** [comment]
+1

**Pull request merged**
